# Lang
language: en

# Dark Mode
dark: true

# Header
menu:
  #To-do: Change home page to /archives
  Home: /
  Archives: /archives
  About: /about

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
#google_analytics:
favicon:
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


# Profile
nickname: curben's blog
description: My personal experiences, mostly in tech stuff.

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  Archives: /archives/
#  globe: 
#  twitter: 
#  github-alt: 
#  youtube-play: 
#  stack-overflow: 
#  google-plus: 
#  rss: 

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content: Lorem ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Archive
post_footer_content: ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Post

# Donate
donate:
  enable: false
  github: 
  paypal: 
  bitcoin: 
  BTCQR: 
  AliPayQR: 
  WeChatQR: 

# Following are configs for various comment system supported by the typing theme
# Gitment
gitment:
  owner:
  repo:
  client:
    id:
    secret:

# Utterances
# NOTICE) make sure the app is installed on the repo before using this commit system
# see https://utteranc.es/ for more
utterances:
  enable: false
  repo: # your repo in this format: 'username/reponame', note that there is no '.git' suffix

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId:  #your leancloud appId
  appKey:  #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn

