# Lang
language: en

# Dark Mode
dark: true

# Header
menu:
  Home: /
  About: /about

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true

# Miscellaneous
favicon:

# Profile
nickname: curben's blog
description: Troubleshooting, tips & tricks, etc.

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  Home: /
#  globe: 
#  twitter: 
#  github-alt: 
#  youtube-play: 
#  stack-overflow: 
#  google-plus: 
#  rss: 

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content:
post_footer_content:

# Donate
donate:
  enable: false
  github: 
  paypal: 
  bitcoin: 
  BTCQR: 
  AliPayQR: 
  WeChatQR: 
