# Lang
language: en

# Dark Mode
dark: true

# Header
menu:
  Home: /
  About: /about
  GitLab: https://gitlab.com/curben/curben.gitlab.io

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true

# Miscellaneous
favicon:

# Profile
nickname: curben's blog
description: Troubleshooting, tips & tricks, etc.

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# Use only the brand icon names (https://fontawesome.com/cheatsheet#brands)
links:
  Home: /
  GitLab: https://gitlab.com/curben/curben.gitlab.io

# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content:
post_footer_content:
