image: node:alpine # Use latest version of Node.js on Alpine

cache: # add cache to 'node_modules' for speeding up builds
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - npm install

test:
  script:
    - apk add patch # Install GNU version of patch for snyk
    - npm run build

  only:
    - master # only trigger when 'master' branch is pushed

renovate: # Check dependency update
  script:
    - npm run renovate

  only:
    - schedules # only triggered by schedules


# # Uncomment below (and comment/remove above) lines for gitlab pages
# image: node:latest # Use latest version of Node.js
# pages:
  # cache: # add cache to 'node_modules' for speeding up builds
    # paths:
      # - node_modules/ # Node modules and dependencies

  # script:
    # - npm install -g snyk hexo-cli
    # - npm install # install node modules
    # - snyk auth $SNYK_TOKEN
    # - snyk protect # Apply patches to node modules
    # - snyk test # Check node modules for vulnerability
    # - hexo deploy # deploy the site.

  # artifacts:
    # paths:
      # - public # deploy to the 'public' folder.

  # only:
    # - master # this job will affect only the 'master' branch
