image: node:latest # Use latest version of Node.js

pages:
  cache: # add cache to 'node_modules' for speeding up builds
    paths:
      - node_modules/ # Node modules and dependencies

  script:
    - npm install -g snyk hexo-cli
    - npm install # install node modules
    - snyk auth $SNYK_TOKEN
    - snyk protect # Apply patches to node modules
    - snyk test # Check node modules for vulnerability
    - hexo deploy # deploy the site
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -execdir gzip -f --keep {} \; # Compress files
  artifacts:
    paths:
      - public # deploy to the 'public' folder
  only:
    - master # this job will affect only the 'master' branch
