image: node:latest # Use latest version of Node.js

pages:
  cache: # add cache to 'node_modules' for speeding up builds
    paths:
      - node_modules/ # Node modules and dependencies

  script:
    - npm install -g snyk hexo-cli
    - npm install # install node modules
    - snyk auth $SNYK_TOKEN
    - snyk protect # Apply patches to node modules
    - snyk test # Check node modules for vulnerability
    # - hexo deploy # deploy the site. Uncomment this line for gitlab pages

  artifacts:
    paths:
      # - public # deploy to the 'public' folder. Uncomment this line for gitlab pages

  only:
    - master # this job will affect only the 'master' branch
