# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Curben
subtitle:
description:
author: curben
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://curben.netlify.com
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: blog
category_dir: categories
code_dir: ''
i18n_dir: :lang
skip_render:
  - 'google5149b8b3449442e3.html'
  - 'yandex_210230bd98a5c664.html'
include:
  - '_headers' # Netlify header rule
  - '_redirects' # Netlify redirects rule

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Tag
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: chameleon

# hexo-nofollow
## https://github.com/curbengh/hexo-nofollow
nofollow:
  enable: true

# hexo-yam
## https://github.com/curbengh/hexo-yam
minify:
  svg:
    plugins: [{cleanupIDs: false}]

feed:
  icon: '/svg/favicon.svg'

## https://github.com/hexojs/hexo/pull/3691
pretty_urls:
  trailing_index: false

# theme config
theme_config:
  # Header
  menu:
    Home: /blog/
    About: /about/
    Feed: /atom.xml
    GitLab: https://gitlab.com/curben/blog

  # Your Feed Location
  # https://github.com/hexojs/hexo-generator-feed
  rss: /atom.xml

  # Profile
  nickname: Curben's blog
  description: Troubleshooting, tips & tricks, etc.

  # Load forkawesome icons? See the links option below.
  icons: false

  # Footer area links
  # If you set "icons: false" link names will be clear text
  # If "icons: true" link names will interpreted as fontawesome icon names
  # Use the forkawesome icon names (https://forkaweso.me/Fork-Awesome/icons/) without the fa- prefix
  links:
    Home: /blog/
    Feed: /atom.xml
    GitLab: https://gitlab.com/curben/blog
