[context.production]
  publish = "public"
  command = "npm run snyk && npm run hexo"

[[headers]]
  for = "/*"
  [headers.value]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
