[context.production]
  publish = "public"
  command = "snyk auth $SNYK_TOKEN && snyk protect && snyk test && hexo generate"

[[headers]]
  for = "/*"
  [headers.value]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.html"
  [headers.value]
    Content-Encoding = "gzip, br"

[[headers]]
  for = "/*.css"
  [headers.value]
    Content-Encoding = "gzip, br"

[[headers]]
  for = "/*.js"
  [headers.value]
    Content-Encoding = "gzip, br"
