[context.production]
  publish = "public"
  command = "snyk auth $SNYK_TOKEN && snyk protect && snyk test && hexo generate"

[[headers]]
  for = "/*"
  [headers.value]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/js/typing.js.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/js/sri-fallback.min.js.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "/css/typing.css.br"
  [headers.values]
    Content-Encoding = "br"

[[redirects]]
  from = "/js/typing.js"
  to = "/js/typing.js.br"
  status = 200
  force = true

[[redirects]]
  from = "/js/sri-fallback.min.js"
  to = "/js/sri-fallback.min.js.br"
  status = 200
  force = true

[[redirects]]
  from = "/css/typing.css"
  to = "/css/typing.css.br"
  status = 200
  force = true

